# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dang_nhap_sai.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dang_nhap_sai(object):
    def setupUi(self, dang_nhap_sai):
        dang_nhap_sai.setObjectName("dang_nhap_sai")
        dang_nhap_sai.resize(800, 400)
        dang_nhap_sai.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(dang_nhap_sai)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dang_ki = QtWidgets.QPushButton(self.centralwidget)
        self.dang_ki.setGeometry(QtCore.QRect(350, 290, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dang_ki.setFont(font)
        self.dang_ki.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"background-color: rgb(170, 255, 0);")
        self.dang_ki.setObjectName("dang_ki")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 300, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.mat_khau = QtWidgets.QLineEdit(self.centralwidget)
        self.mat_khau.setGeometry(QtCore.QRect(330, 170, 311, 41))
        self.mat_khau.setText("")
        self.mat_khau.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mat_khau.setClearButtonEnabled(True)
        self.mat_khau.setObjectName("mat_khau")
        self.doi_mk = QtWidgets.QPushButton(self.centralwidget)
        self.doi_mk.setGeometry(QtCore.QRect(350, 340, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doi_mk.setFont(font)
        self.doi_mk.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(255, 0, 0);")
        self.doi_mk.setObjectName("doi_mk")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tai_khoan = QtWidgets.QLineEdit(self.centralwidget)
        self.tai_khoan.setGeometry(QtCore.QRect(330, 80, 311, 41))
        self.tai_khoan.setText("")
        self.tai_khoan.setClearButtonEnabled(True)
        self.tai_khoan.setObjectName("tai_khoan")
        self.dang_nhap_tk = QtWidgets.QPushButton(self.centralwidget)
        self.dang_nhap_tk.setGeometry(QtCore.QRect(500, 220, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dang_nhap_tk.setFont(font)
        self.dang_nhap_tk.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.dang_nhap_tk.setObjectName("dang_nhap_tk")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 340, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 230, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(500, 300, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.forgoted_mk = QtWidgets.QPushButton(self.centralwidget)
        self.forgoted_mk.setGeometry(QtCore.QRect(650, 290, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.forgoted_mk.setFont(font)
        self.forgoted_mk.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"background-color: rgb(255, 255, 127);")
        self.forgoted_mk.setObjectName("forgoted_mk")
        dang_nhap_sai.setCentralWidget(self.centralwidget)

        self.retranslateUi(dang_nhap_sai)
        QtCore.QMetaObject.connectSlotsByName(dang_nhap_sai)

    def retranslateUi(self, dang_nhap_sai):
        _translate = QtCore.QCoreApplication.translate
        dang_nhap_sai.setWindowTitle(_translate("dang_nhap_sai", "Đăng Nhập"))
        self.label.setText(_translate("dang_nhap_sai", "Tài Khoản : "))
        self.label_3.setText(_translate("dang_nhap_sai", "Mật Khẩu  : "))
        self.dang_ki.setText(_translate("dang_nhap_sai", "Đăng kí"))
        self.label_4.setText(_translate("dang_nhap_sai", "Chưa có tài khoản?"))
        self.mat_khau.setPlaceholderText(_translate("dang_nhap_sai", "Enter PassWord"))
        self.doi_mk.setText(_translate("dang_nhap_sai", "Đổi Mật Khẩu"))
        self.label_2.setText(_translate("dang_nhap_sai", "Đăng Nhập"))
        self.tai_khoan.setPlaceholderText(_translate("dang_nhap_sai", "Enter User Name"))
        self.dang_nhap_tk.setText(_translate("dang_nhap_sai", "Đăng Nhập"))
        self.label_5.setText(_translate("dang_nhap_sai", "Quên Mật Khẩu ? "))
        self.label_6.setText(_translate("dang_nhap_sai", "<html><head/><body><p><span style=\" color:#ff0000;\">Tài Khoản Hoặc Mật Khẩu Sai !</span></p></body></html>"))
        self.label_7.setText(_translate("dang_nhap_sai", "Quên Mật Khẩu?"))
        self.forgoted_mk.setText(_translate("dang_nhap_sai", "Quên Mật Khẩu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dang_nhap_sai = QtWidgets.QMainWindow()
    ui = Ui_dang_nhap_sai()
    ui.setupUi(dang_nhap_sai)
    dang_nhap_sai.show()
    sys.exit(app.exec_())
