# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dang_ki.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dang_ki(object):
    def setupUi(self, dang_ki):
        dang_ki.setObjectName("dang_ki")
        dang_ki.resize(800, 400)
        dang_ki.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(dang_ki)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dang_ki_2 = QtWidgets.QPushButton(self.centralwidget)
        self.dang_ki_2.setGeometry(QtCore.QRect(520, 280, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dang_ki_2.setFont(font)
        self.dang_ki_2.setStyleSheet("\n"
"background-color: rgb(85, 255, 255);")
        self.dang_ki_2.setObjectName("dang_ki_2")
        self.mat_khau_dang_ki = QtWidgets.QLineEdit(self.centralwidget)
        self.mat_khau_dang_ki.setGeometry(QtCore.QRect(350, 120, 311, 41))
        self.mat_khau_dang_ki.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mat_khau_dang_ki.setClearButtonEnabled(True)
        self.mat_khau_dang_ki.setObjectName("mat_khau_dang_ki")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tai_khoan_dang_ki = QtWidgets.QLineEdit(self.centralwidget)
        self.tai_khoan_dang_ki.setGeometry(QtCore.QRect(350, 70, 311, 41))
        self.tai_khoan_dang_ki.setClearButtonEnabled(True)
        self.tai_khoan_dang_ki.setObjectName("tai_khoan_dang_ki")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 180, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.mat_khau_dang_ki_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.mat_khau_dang_ki_2.setGeometry(QtCore.QRect(350, 170, 311, 41))
        self.mat_khau_dang_ki_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mat_khau_dang_ki_2.setClearButtonEnabled(True)
        self.mat_khau_dang_ki_2.setObjectName("mat_khau_dang_ki_2")
        self.back_dn = QtWidgets.QPushButton(self.centralwidget)
        self.back_dn.setGeometry(QtCore.QRect(130, 280, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.back_dn.setFont(font)
        self.back_dn.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.back_dn.setObjectName("back_dn")
        dang_ki.setCentralWidget(self.centralwidget)

        self.retranslateUi(dang_ki)
        QtCore.QMetaObject.connectSlotsByName(dang_ki)

    def retranslateUi(self, dang_ki):
        _translate = QtCore.QCoreApplication.translate
        dang_ki.setWindowTitle(_translate("dang_ki", "Đăng Kí"))
        self.label.setText(_translate("dang_ki", "Tài Khoản : "))
        self.label_3.setText(_translate("dang_ki", "Mật Khẩu  : "))
        self.dang_ki_2.setText(_translate("dang_ki", "Đăng kí"))
        self.mat_khau_dang_ki.setPlaceholderText(_translate("dang_ki", "Enter PassWord "))
        self.label_2.setText(_translate("dang_ki", "Đăng Kí"))
        self.tai_khoan_dang_ki.setPlaceholderText(_translate("dang_ki", "Enter User Name"))
        self.label_6.setText(_translate("dang_ki", "Nhập Lại Mật Khẩu :"))
        self.mat_khau_dang_ki_2.setPlaceholderText(_translate("dang_ki", "Enter PassWord Again"))
        self.back_dn.setText(_translate("dang_ki", "Trở Về"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dang_ki = QtWidgets.QMainWindow()
    ui = Ui_dang_ki()
    ui.setupUi(dang_ki)
    dang_ki.show()
    sys.exit(app.exec_())
