# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dang_nhap.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dang_nhap(object):
    def setupUi(self, Dang_nhap):
        Dang_nhap.setObjectName("Dang_nhap")
        Dang_nhap.resize(800, 401)
        Dang_nhap.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Dang_nhap)
        self.centralwidget.setObjectName("centralwidget")
        self.doi_mk = QtWidgets.QPushButton(self.centralwidget)
        self.doi_mk.setGeometry(QtCore.QRect(350, 340, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doi_mk.setFont(font)
        self.doi_mk.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(255, 0, 0);")
        self.doi_mk.setObjectName("doi_mk")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tai_khoan = QtWidgets.QLineEdit(self.centralwidget)
        self.tai_khoan.setGeometry(QtCore.QRect(330, 80, 311, 41))
        self.tai_khoan.setClearButtonEnabled(True)
        self.tai_khoan.setObjectName("tai_khoan")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.mat_khau = QtWidgets.QLineEdit(self.centralwidget)
        self.mat_khau.setGeometry(QtCore.QRect(330, 170, 311, 41))
        self.mat_khau.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mat_khau.setClearButtonEnabled(True)
        self.mat_khau.setObjectName("mat_khau")
        self.dang_nhap = QtWidgets.QPushButton(self.centralwidget)
        self.dang_nhap.setGeometry(QtCore.QRect(500, 220, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dang_nhap.setFont(font)
        self.dang_nhap.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.dang_nhap.setObjectName("dang_nhap")
        self.dang_ki = QtWidgets.QPushButton(self.centralwidget)
        self.dang_ki.setGeometry(QtCore.QRect(350, 290, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dang_ki.setFont(font)
        self.dang_ki.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"background-color: rgb(170, 255, 127);")
        self.dang_ki.setObjectName("dang_ki")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 300, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 340, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.forgoted_mk = QtWidgets.QPushButton(self.centralwidget)
        self.forgoted_mk.setGeometry(QtCore.QRect(650, 290, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.forgoted_mk.setFont(font)
        self.forgoted_mk.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"background-color: rgb(255, 255, 127);")
        self.forgoted_mk.setObjectName("forgoted_mk")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(500, 300, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        Dang_nhap.setCentralWidget(self.centralwidget)

        self.retranslateUi(Dang_nhap)
        QtCore.QMetaObject.connectSlotsByName(Dang_nhap)

    def retranslateUi(self, Dang_nhap):
        _translate = QtCore.QCoreApplication.translate
        Dang_nhap.setWindowTitle(_translate("Dang_nhap", "Đăng Nhập"))
        self.doi_mk.setText(_translate("Dang_nhap", "Đổi Mật Khẩu"))
        self.label.setText(_translate("Dang_nhap", "Tài Khoản : "))
        self.label_2.setText(_translate("Dang_nhap", "Đăng Nhập"))
        self.tai_khoan.setPlaceholderText(_translate("Dang_nhap", "Enter User Name"))
        self.label_3.setText(_translate("Dang_nhap", "Mật Khẩu  : "))
        self.mat_khau.setPlaceholderText(_translate("Dang_nhap", "Enter PassWord"))
        self.dang_nhap.setText(_translate("Dang_nhap", "Đăng Nhập"))
        self.dang_ki.setText(_translate("Dang_nhap", "Đăng kí"))
        self.label_4.setText(_translate("Dang_nhap", "Chưa có tài khoản?"))
        self.label_5.setText(_translate("Dang_nhap", "Quên Mật Khẩu ? "))
        self.forgoted_mk.setText(_translate("Dang_nhap", "Quên Mật Khẩu"))
        self.label_7.setText(_translate("Dang_nhap", "Quên Mật Khẩu?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dang_nhap = QtWidgets.QMainWindow()
    ui = Ui_Dang_nhap()
    ui.setupUi(Dang_nhap)
    Dang_nhap.show()
    sys.exit(app.exec_())
