# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dang_xuat.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dang_xuat(object):
    def setupUi(self, dang_xuat):
        dang_xuat.setObjectName("dang_xuat")
        dang_xuat.resize(600, 300)
        dang_xuat.setStyleSheet("background-color: rgb(218, 166, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(dang_xuat)
        self.centralwidget.setObjectName("centralwidget")
        self.tro_ve = QtWidgets.QPushButton(self.centralwidget)
        self.tro_ve.setGeometry(QtCore.QRect(70, 207, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tro_ve.setFont(font)
        self.tro_ve.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 0);")
        self.tro_ve.setObjectName("tro_ve")
        self.dang_xuat_han = QtWidgets.QPushButton(self.centralwidget)
        self.dang_xuat_han.setGeometry(QtCore.QRect(402, 207, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dang_xuat_han.setFont(font)
        self.dang_xuat_han.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.dang_xuat_han.setObjectName("dang_xuat_han")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 30, 461, 141))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        dang_xuat.setCentralWidget(self.centralwidget)

        self.retranslateUi(dang_xuat)
        QtCore.QMetaObject.connectSlotsByName(dang_xuat)

    def retranslateUi(self, dang_xuat):
        _translate = QtCore.QCoreApplication.translate
        dang_xuat.setWindowTitle(_translate("dang_xuat", "Đăng Xuất"))
        self.tro_ve.setText(_translate("dang_xuat", "Trở Về"))
        self.dang_xuat_han.setText(_translate("dang_xuat", "Đăng Xuất"))
        self.label.setText(_translate("dang_xuat", "     Bạn Chắn Chắn Muốn Đăng Xuất?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dang_xuat = QtWidgets.QMainWindow()
    ui = Ui_dang_xuat()
    ui.setupUi(dang_xuat)
    dang_xuat.show()
    sys.exit(app.exec_())
