# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doi_mat_khau.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_doi_mk(object):
    def setupUi(self, doi_mk):
        doi_mk.setObjectName("doi_mk")
        doi_mk.resize(800, 400)
        doi_mk.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(doi_mk)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 70, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 170, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.xac_nhan = QtWidgets.QPushButton(self.centralwidget)
        self.xac_nhan.setGeometry(QtCore.QRect(520, 280, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.xac_nhan.setFont(font)
        self.xac_nhan.setStyleSheet("\n"
"background-color: rgb(85, 255, 255);")
        self.xac_nhan.setObjectName("xac_nhan")
        self.mat_khau_dang_ki = QtWidgets.QLineEdit(self.centralwidget)
        self.mat_khau_dang_ki.setGeometry(QtCore.QRect(350, 170, 311, 41))
        self.mat_khau_dang_ki.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mat_khau_dang_ki.setClearButtonEnabled(True)
        self.mat_khau_dang_ki.setObjectName("mat_khau_dang_ki")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tai_khoan_dang_ki = QtWidgets.QLineEdit(self.centralwidget)
        self.tai_khoan_dang_ki.setGeometry(QtCore.QRect(350, 70, 311, 41))
        self.tai_khoan_dang_ki.setClearButtonEnabled(True)
        self.tai_khoan_dang_ki.setObjectName("tai_khoan_dang_ki")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 230, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.mat_khau_dang_ki_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.mat_khau_dang_ki_2.setGeometry(QtCore.QRect(350, 220, 311, 41))
        self.mat_khau_dang_ki_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mat_khau_dang_ki_2.setClearButtonEnabled(True)
        self.mat_khau_dang_ki_2.setObjectName("mat_khau_dang_ki_2")
        self.mat_khau_cu = QtWidgets.QLineEdit(self.centralwidget)
        self.mat_khau_cu.setGeometry(QtCore.QRect(350, 120, 311, 41))
        self.mat_khau_cu.setText("")
        self.mat_khau_cu.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mat_khau_cu.setClearButtonEnabled(True)
        self.mat_khau_cu.setObjectName("mat_khau_cu")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(140, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.back_dn = QtWidgets.QPushButton(self.centralwidget)
        self.back_dn.setGeometry(QtCore.QRect(130, 280, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.back_dn.setFont(font)
        self.back_dn.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.back_dn.setObjectName("back_dn")
        doi_mk.setCentralWidget(self.centralwidget)

        self.retranslateUi(doi_mk)
        QtCore.QMetaObject.connectSlotsByName(doi_mk)

    def retranslateUi(self, doi_mk):
        _translate = QtCore.QCoreApplication.translate
        doi_mk.setWindowTitle(_translate("doi_mk", "Đổi Mật Khẩu"))
        self.label.setText(_translate("doi_mk", "Tài Khoản : "))
        self.label_3.setText(_translate("doi_mk", "Mật Khẩu mới : "))
        self.xac_nhan.setText(_translate("doi_mk", "Xác Nhận"))
        self.mat_khau_dang_ki.setPlaceholderText(_translate("doi_mk", "Enter PassWord"))
        self.label_2.setText(_translate("doi_mk", "Đổi Mật Khẩu"))
        self.tai_khoan_dang_ki.setPlaceholderText(_translate("doi_mk", "Enter User Name"))
        self.label_6.setText(_translate("doi_mk", "Nhập Lại Mật Khẩu :"))
        self.mat_khau_dang_ki_2.setPlaceholderText(_translate("doi_mk", "Enter PassWord Again"))
        self.mat_khau_cu.setPlaceholderText(_translate("doi_mk", "Enter PassWord"))
        self.label_4.setText(_translate("doi_mk", "Mật Khẩu cũ : "))
        self.back_dn.setText(_translate("doi_mk", "Trở Về"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    doi_mk = QtWidgets.QMainWindow()
    ui = Ui_doi_mk()
    ui.setupUi(doi_mk)
    doi_mk.show()
    sys.exit(app.exec_())
