# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trang_chu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_trang_chu(object):
    def setupUi(self, trang_chu):
        trang_chu.setObjectName("trang_chu")
        trang_chu.resize(1031, 811)
        trang_chu.setStyleSheet("background-color: rgb(0, 0, 216);")
        self.centralwidget = QtWidgets.QWidget(trang_chu)
        self.centralwidget.setObjectName("centralwidget")
        self.food = QtWidgets.QPushButton(self.centralwidget)
        self.food.setGeometry(QtCore.QRect(150, 240, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.food.setFont(font)
        self.food.setStyleSheet("\n"
"background-color: rgb(85, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.food.setObjectName("food")
        self.account = QtWidgets.QPushButton(self.centralwidget)
        self.account.setGeometry(QtCore.QRect(530, 680, 501, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.account.setFont(font)
        self.account.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.account.setObjectName("account")
        self.check = QtWidgets.QPushButton(self.centralwidget)
        self.check.setGeometry(QtCore.QRect(150, 600, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.check.setFont(font)
        self.check.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.check.setObjectName("check")
        self.main = QtWidgets.QPushButton(self.centralwidget)
        self.main.setGeometry(QtCore.QRect(0, 680, 531, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main.setFont(font)
        self.main.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main.setObjectName("main")
        self.menu = QtWidgets.QPushButton(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(680, 240, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.menu.setFont(font)
        self.menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.menu.setObjectName("menu")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 700, 101, 101))
        self.label.setStyleSheet("border-image: url(:/picture/399673683_310250778538086_6690215168702423102_n.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 20, 231, 211))
        self.label_2.setStyleSheet("border-image: url(:/picture/394699555_320747427253059_444095948765987737_n.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 20, 231, 211))
        self.label_3.setStyleSheet("border-image: url(:/picture/399751874_285777313801879_3569131284148977916_n.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 380, 231, 211))
        self.label_4.setStyleSheet("border-image: url(:/picture/399748326_706550711374268_5590998621727746705_n.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(680, 600, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exit.setFont(font)
        self.exit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 0, 0);")
        self.exit.setObjectName("exit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(680, 380, 231, 211))
        self.label_5.setStyleSheet("border-image: url(:/picture/th.jpg);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        trang_chu.setCentralWidget(self.centralwidget)

        self.retranslateUi(trang_chu)
        QtCore.QMetaObject.connectSlotsByName(trang_chu)

    def retranslateUi(self, trang_chu):
        _translate = QtCore.QCoreApplication.translate
        trang_chu.setWindowTitle(_translate("trang_chu", "Trang_chủ"))
        self.food.setText(_translate("trang_chu", "Gọi Món"))
        self.account.setText(_translate("trang_chu", "Tài Khoản"))
        self.check.setText(_translate("trang_chu", "Hóa Đơn"))
        self.main.setText(_translate("trang_chu", "Trang chủ"))
        self.menu.setText(_translate("trang_chu", "MENU"))
        self.exit.setText(_translate("trang_chu", "Đăng Xuất"))
import add_image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trang_chu = QtWidgets.QMainWindow()
    ui = Ui_trang_chu()
    ui.setupUi(trang_chu)
    trang_chu.show()
    sys.exit(app.exec_())
